from .aws import *

################### Azure

AZURE_ACCOUNT_NAME =  AUTH_TOKENS.get('AZURE_ACCOUNT_NAME', None)
AZURE_ACCOUNT_KEY = AUTH_TOKENS.get('AZURE_ACCOUNT_KEY', None)
AZURE_CONTAINER = AUTH_TOKENS.get('AZURE_CONTAINER', None)

ORA2_FILEUPLOAD_BACKEND = "django"

if AZURE_ACCOUNT_NAME and AZURE_ACCOUNT_KEY and AZURE_CONTAINER:
    DEFAULT_FILE_STORAGE = 'openedx.core.storage.AzureStorageExtended'

EXTERNAL_CERTIFICATES_ORG_DISPLAY_NAMES = ENV_TOKENS.get('EXTERNAL_CERTIFICATES_ORG_DISPLAY_NAMES', EXTERNAL_CERTIFICATES_ORG_DISPLAY_NAMES)
EXTERNAL_CERTIFICATES_HTTP_REFERERS = ENV_TOKENS.get('EXTERNAL_CERTIFICATES_HTTP_REFERERS', EXTERNAL_CERTIFICATES_HTTP_REFERERS)
EXTERNAL_CERTIFICATES_HTTP_USER_AGENT = ENV_TOKENS.get('EXTERNAL_CERTIFICATES_HTTP_USER_AGENT', EXTERNAL_CERTIFICATES_HTTP_USER_AGENT)
EXTERNAL_CERTIFICATES_IPS_SUBNETS = ENV_TOKENS.get('EXTERNAL_CERTIFICATES_IPS_SUBNETS', EXTERNAL_CERTIFICATES_IPS_SUBNETS)
EXTERNAL_CERTIFICATES_INTERVENTION_DEBUG = ENV_TOKENS.get('EXTERNAL_CERTIFICATES_INTERVENTION_DEBUG', EXTERNAL_CERTIFICATES_INTERVENTION_DEBUG)
