# -*- coding: utf-8 -*-
from __future__ import unicode_literals


AFFILIATIONS = [
    "Stanford Children's Health",
    "Packard Children's Health Alliance (PCHA)",
    'Stanford Health Care',
    'Stanford University',
    'University Healthcare Alliance (UHA)',
    'Not affiliated with Stanford Medicine',
]
SPECIALTIES = [
    {
        'display': 'Allergy, Immunology, & Rheumatology',
        'key': 'Allergy,_Immunology,_&_Rheumatology',
    },
    {
        'display': 'Anesthesiology',
    },
    {
        'display': 'Cardiovascular Health',
        'key': 'Cardiovascular_Health',
        'sub_specialties': [
            ('Cardiac_Surgery', 'Cardiac Surgery'),
            ('Cardiology', 'Cardiology'),
            ('Cardiothoracic', 'Cardiothoracic'),
            ('Cardiothoracic_Surgery', 'Cardiothoracic Surgery'),
            ('Cardiovascular_Disease', 'Cardiovascular Disease'),
            ('Cath_Angio/Lab', 'Cath Angio/Lab'),
            ('Electrophysiology', 'Electrophysiology'),
            ('Interventional_Cardiology', 'Interventional Cardiology'),
        ],
    },
    {
        'display': 'Complimentary Medicine & Pain Management',
        'key': 'Complimentary_Medicine_&_Pain_Management',
    },
    {
        'display': 'Critical Care & Pulmonology',
        'key': 'Critical_Care_&_Pulmonology',
    },
    {
        'display': 'Dental Specialties',
        'key': 'Dental_Specialties',
    },
    {
        'display': 'Dermatology',
    },
    {
        'display': 'Emergency Medicine & Trauma',
        'key': 'Emergency_Medicine_&_Trauma',
    },
    {
        'display': 'Endocrinology & Metabolism',
        'key': 'Endocrinology_&_Metabolism',
    },
    {
        'display': 'Family Medicine & Community Health',
        'key': 'Family_Medicine_&_Community_Health',
    },
    {
        'display': 'Gastroenterology & Hepatology',
        'key': 'Gastroenterology_&_Hepatology',
    },
    {
        'display': 'Genetics & Genomics',
        'key': 'Genetics_&_Genomics',
    },
    {
        'display': 'Gerontology',
    },
    {
        'display': 'Hematology',
    },
    {
        'display': 'Infectious Disease & Global Health',
        'key': 'Infectious_Disease_&_Global_Health',
    },
    {
        'display': 'Internal Medicine',
        'key': 'Internal_Medicine',
        'sub_specialties': [
            ('Adolescent_Medicine', 'Adolescent Medicine'),
            ('Adult_Congenital_Heart_Disease', 'Adult Congenital Heart Disease'),
            ('Advanced_Heart_Failure_and_Transplant_Cardiology', 'Advanced Heart Failure and Transplant Cardiology'),
            ('Allergy_&_Immunology', 'Allergy & Immunology'),
            ('Cardiovascular_Disease', 'Cardiovascular Disease'),
            ('Clinical_Cardiac_Electrophysiology', 'Clinical Cardiac Electrophysiology'),
            ('Critical_Care_Medicine', 'Critical Care Medicine'),
            ('Endocrinology,_Diabetes,_&_Metabolism', 'Endocrinology, Diabetes, & Metabolism'),
            ('Gastroenterology', 'Gastroenterology'),
            ('Geriatric_Medicine', 'Geriatric Medicine'),
            ('Hematology', 'Hematology'),
            ('Hospice_&_Palliative_Medicine', 'Hospice & Palliative Medicine'),
            ('Hospital_Medicine,_Focused_Practice', 'Hospital Medicine, Focused Practice'),
            ('Infectious_Disease', 'Infectious Disease'),
            ('Interventional_Cardiology', 'Interventional Cardiology'),
            ('Medical_Oncology', 'Medical Oncology'),
            ('Nephrology', 'Nephrology'),
            ('Pulmonary_Disease', 'Pulmonary Disease'),
            ('Rheumatology', 'Rheumatology'),
            ('Sleep_Medicine', 'Sleep Medicine'),
            ('Sports_Medicine', 'Sports Medicine'),
        ],
    },
    {
        'display': 'Nephrology',
    },
    {
        'display': 'Neurology & Neurologic Surgery',
        'key': 'Neurology_&_Neurologic_Surgery',
    },
    {
        'display': 'Obstetrics & Gynecology',
        'key': 'Obstetrics_&_Gynecology',
        'sub_specialties': [
            ('Female_Pelvic_Medicine_and_Reconstructive_Surgery', 'Female Pelvic Medicine and Reconstructive Surgery'),
            ('Gynecologic_Oncology', 'Gynecologic Oncology'),
            ('Maternal-Fetal_Medicine', 'Maternal-Fetal Medicine'),
            ('Reproductive_Endocrinology_and_Infertility', 'Reproductive Endocrinology and Infertility'),
        ],
    },
    {
        'display': 'Oncology',
        'sub_specialties': [
            ('Hematology', 'Hematology'),
            ('Medical_Oncology', 'Medical Oncology'),
            ('Radiation_Oncology', 'Radiation Oncology'),
        ],
    },
    {
        'display': 'Ophthalmology',
    },
    {
        'display': 'Orthopedics & Sports Medicine',
        'key': 'Orthopedics_&_Sports_Medicine',
        'sub_specialties': [
            ('Surgery', 'Surgery'),
        ],
    },
    {
        'display': 'Otolaryngology (ENT)',
        'key': 'Otolaryngology_(ENT)',
    },
    {
        'display': 'Pathology & Laboratory Medicine',
        'key': 'Pathology_&_Laboratory_Medicine',
    },
    {
        'display': 'Pediatrics',
        'sub_specialties': [
            ('Adolescent_Medicine', 'Adolescent Medicine'),
            ('Allergy,_Immunology,_&_Rheumatology', 'Allergy, Immunology, & Rheumatology'),
            ('Anesthesiology', 'Anesthesiology'),
            ('Cardiovascular_Health', 'Cardiovascular Health'),
            ('Complimentary_Medicine_&_Pain_Management', 'Complimentary Medicine & Pain Management'),
            ('Critical_Care_&_Pulmonology', 'Critical Care & Pulmonology'),
            ('Dental_Specialties', 'Dental Specialties'),
            ('Dermatology', 'Dermatology'),
            ('Emergency_Medicine_&_Trauma', 'Emergency Medicine & Trauma'),
            ('Endocrinology_&_Metabolism', ' Endocrinology & Metabolism'),
            ('Family_Medicine_&_Community_Health', 'Family Medicine & Community Health'),
            ('Gastroenterology_&_Hepatology', 'Gastroenterology & Hepatology'),
            ('Genetics_&_Genomics', 'Genetics & Genomics'),
            ('Gerontology', 'Gerontology'),
            ('Hematology', 'Hematology'),
            ('Infectious_Disease_&_Global_Health', 'Infectious Disease & Global Health'),
            ('Internal_Medicine', 'Internal Medicine'),
            ('Neonatology', 'Neonatology'),
            ('Nephrology', 'Nephrology'),
            ('Neurology_&_Neurologic_Surgery', 'Neurology & Neurologic Surgery'),
            ('Obstetrics_&_Gynecology', 'Obstetrics & Gynecology'),
            ('Oncology', 'Oncology'),
            ('Ophthalmology', 'Ophthalmology'),
            ('Orthopedics_&_Sports_Medicine', 'Orthopedics & Sports Medicine'),
            ('Otolaryngology_(ENT)', 'Otolaryngology (ENT)'),
            ('Pathology_&_Laboratory_Medicine', 'Pathology & Laboratory Medicine'),
            ('Preventative_Medicine_&_Nutrition', 'Preventative Medicine & Nutrition'),
            ('Psychiatry_&_Behavioral_Sciences', 'Psychiatry & Behavioral Sciences'),
            ('Radiology', 'Radiology'),
            ('Surgery', 'Surgery'),
            ('Urology', 'Urology'),
            ('Other/None', 'Other/None'),
        ],
    },
    {
        'display': 'Preventative Medicine & Nutrition',
        'key': 'Preventative_Medicine_&_Nutrition',
    },
    {
        'display': 'Psychiatry & Behavioral Sciences',
        'key': 'Psychiatry_&_Behavioral_Sciences',
    },
    {
        'display': 'Radiology',
        'sub_specialties': [
            ('Diagnostic_Radiology', 'Diagnostic Radiology'),
            ('Interventional_Radiology_and_Diagnostic_Radiology', 'Interventional Radiology and Diagnostic Radiology'),
            ('Medical_Physics', 'Medical Physics'),
            ('Radiation_Oncology', 'Radiation Oncology'),
            ('Therapeutic_Medical_Physics', 'Therapeutic Medical Physics'),
        ],
    },
    {
        'display': 'Surgery',
        'sub_specialties': [
            ('Complex_General_Surgical_Oncology', 'Complex General Surgical Oncology'),
            ('General_Surgery', 'General Surgery'),
            ('Hand_Surgery', 'Hand Surgery'),
            ('Hospice_and_Palliative_Medicine', 'Hospice and Palliative Medicine'),
            ('Pediatric_Surgery', 'Pediatric Surgery'),
            ('Surgical_Critical_Care', 'Surgical Critical Care'),
            ('Vascular_Surgery', 'Vascular Surgery'),
        ],
    },
    {
        'display': 'Urology',
    },
    {
        'display': 'Other/None',
    },
]
COUNTRY_CHOICES = (
    ('United States', 'United States'),
    ('Afghanistan', 'Afghanistan'),
    ('Aland Islands', 'Aland Islands'),
    ('Albania', 'Albania'),
    ('Algeria', 'Algeria'),
    ('American Samoa', 'American Samoa'),
    ('Andorra', 'Andorra'),
    ('Angola', 'Angola'),
    ('Anguilla', 'Anguilla'),
    ('Antarctica', 'Antarctica'),
    ('Antigua And Barbuda', 'Antigua And Barbuda'),
    ('Argentina', 'Argentina'),
    ('Armenia', 'Armenia'),
    ('Aruba', 'Aruba'),
    ('Australia', 'Australia'),
    ('Austria', 'Austria'),
    ('Azerbaijan', 'Azerbaijan'),
    ('Bahamas', 'Bahamas'),
    ('Bahrain', 'Bahrain'),
    ('Bangladesh', 'Bangladesh'),
    ('Barbados', 'Barbados'),
    ('Belarus', 'Belarus'),
    ('Belgium', 'Belgium'),
    ('Belize', 'Belize'),
    ('Benin', 'Benin'),
    ('Bermuda', 'Bermuda'),
    ('Bhutan', 'Bhutan'),
    ('Bolivia', 'Bolivia'),
    ('Bosnia And Herzegovina', 'Bosnia And Herzegovina'),
    ('Botswana', 'Botswana'),
    ('Bouvet Island', 'Bouvet Island'),
    ('Brazil', 'Brazil'),
    ('British Indian Ocean Territory', 'British Indian Ocean Territory'),
    ('Brunei Darussalam', 'Brunei Darussalam'),
    ('Bulgaria', 'Bulgaria'),
    ('Burkina Faso', 'Burkina Faso'),
    ('Burundi', 'Burundi'),
    ('Cambodia', 'Cambodia'),
    ('Cameroon', 'Cameroon'),
    ('Canada', 'Canada'),
    ('Cape Verde', 'Cape Verde'),
    ('Cayman Islands', 'Cayman Islands'),
    ('Central African Republic', 'Central African Republic'),
    ('Chad', 'Chad'),
    ('Chile', 'Chile'),
    ('China', 'China'),
    ('Christmas Island', 'Christmas Island'),
    ('Cocos (Keeling) Islands', 'Cocos (Keeling) Islands'),
    ('Colombia', 'Colombia'),
    ('Comoros', 'Comoros'),
    ('Congo', 'Congo'),
    ('Congo, The Democratic Republic OfThe', 'Congo, The Democratic Republic OfThe'),
    ('Cook Islands', 'Cook Islands'),
    ('Costa Rica', 'Costa Rica'),
    ("Cote D'lvoire", "Cote D'lvoire"),
    ('Croatia', 'Croatia'),
    ('Cuba', 'Cuba'),
    ('Cyprus', 'Cyprus'),
    ('Czech Republic', 'Czech Republic'),
    ('Denmark', 'Denmark'),
    ('Djibouti', 'Djibouti'),
    ('Dominica', 'Dominica'),
    ('Dominican Republic', 'Dominican Republic'),
    ('Ecuador', 'Ecuador'),
    ('Egypt', 'Egypt'),
    ('El Salvador', 'El Salvador'),
    ('Equatorial Guinea', 'Equatorial Guinea'),
    ('Eritrea', 'Eritrea'),
    ('Estonia', 'Estonia'),
    ('Ethiopia', 'Ethiopia'),
    ('Falkland Islands (Malvinas)', 'Falkland Islands (Malvinas)'),
    ('Faroe Islands', 'Faroe Islands'),
    ('Fiji', 'Fiji'),
    ('Finland', 'Finland'),
    ('France', 'France'),
    ('French Guiana', 'French Guiana'),
    ('French Polynesia', 'French Polynesia'),
    ('French Southern Territories', 'French Southern Territories'),
    ('Gabon', 'Gabon'),
    ('Gambia', 'Gambia'),
    ('Georgia', 'Georgia'),
    ('Germany', 'Germany'),
    ('Ghana', 'Ghana'),
    ('Gibraltar', 'Gibraltar'),
    ('Greece', 'Greece'),
    ('Greenland', 'Greenland'),
    ('Grenada', 'Grenada'),
    ('Guadeloupe', 'Guadeloupe'),
    ('Guam', 'Guam'),
    ('Guatemala', 'Guatemala'),
    ('Guernsey', 'Guernsey'),
    ('Guinea', 'Guinea'),
    ('Guinea-Bissau', 'Guinea-Bissau'),
    ('Guyana', 'Guyana'),
    ('Haiti', 'Haiti'),
    ('Heard Island And McDonald Is lands', 'Heard Island And McDonald Is lands'),
    ('Holy See (Vatican City State)', 'Holy See (Vatican City State)'),
    ('Honduras', 'Honduras'),
    ('Hong Kong', 'Hong Kong'),
    ('Hungary', 'Hungary'),
    ('Iceland', 'Iceland'),
    ('India', 'India'),
    ('Indonesia', 'Indonesia'),
    ('Iran, Islamic Republic Of', 'Iran, Islamic Republic Of'),
    ('Iraq', 'Iraq'),
    ('Ireland', 'Ireland'),
    ('Isle Of Man', 'Isle Of Man'),
    ('Israel', 'Israel'),
    ('Italy', 'Italy'),
    ('Jamaica', 'Jamaica'),
    ('Japan', 'Japan'),
    ('Jersey', 'Jersey'),
    ('Jordan', 'Jordan'),
    ('Kazakhstan', 'Kazakhstan'),
    ('Kenya', 'Kenya'),
    ('Kiribati', 'Kiribati'),
    ("Korea, Democratic People's Republic Of", "Korea, Democratic People's Republic Of"),
    ('Korea, Republic Of', 'Korea, Republic Of'),
    ('Kuwait', 'Kuwait'),
    ('Kyrgyzstan', 'Kyrgyzstan'),
    ("Lao People's Democratic Republic", "Lao People's Democratic Republic"),
    ('Latvia', 'Latvia'),
    ('Lebanon', 'Lebanon'),
    ('Lesotho', 'Lesotho'),
    ('Liberia', 'Liberia'),
    ('Libyan Arab Jamahiriya', 'Libyan Arab Jamahiriya'),
    ('Liechtenstein', 'Liechtenstein'),
    ('Lithuania', 'Lithuania'),
    ('Luxembourg', 'Luxembourg'),
    ('Macao', 'Macao'),
    ('Macedonia, The Former Yugoslav Republic Of', 'Macedonia, The Former Yugoslav Republic Of'),
    ('Madagascar', 'Madagascar'),
    ('Malawi', 'Malawi'),
    ('Malaysia', 'Malaysia'),
    ('Maldives', 'Maldives'),
    ('Mali', 'Mali'),
    ('Malta', 'Malta'),
    ('Marshall Islands', 'Marshall Islands'),
    ('Martinique', 'Martinique'),
    ('Mauritania', 'Mauritania'),
    ('Mauritius', 'Mauritius'),
    ('Mayotte', 'Mayotte'),
    ('Mexico', 'Mexico'),
    ('Micronesia, Federated States Of', 'Micronesia, Federated States Of'),
    ('Moldova, Republic Of', 'Moldova, Republic Of'),
    ('Monaco', 'Monaco'),
    ('Mongolia', 'Mongolia'),
    ('Montenegro', 'Montenegro'),
    ('Montserrat', 'Montserrat'),
    ('Morocco', 'Morocco'),
    ('Mozambique', 'Mozambique'),
    ('Myanmar', 'Myanmar'),
    ('Namibia', 'Namibia'),
    ('Nauru', 'Nauru'),
    ('Nepal', 'Nepal'),
    ('Netherlands', 'Netherlands'),
    ('Netherlands Antilles', 'Netherlands Antilles'),
    ('New Caledonia', 'New Caledonia'),
    ('New Zealand', 'New Zealand'),
    ('Nicaragua', 'Nicaragua'),
    ('Niger', 'Niger'),
    ('Nigeria', 'Nigeria'),
    ('Niue', 'Niue'),
    ('Norfolk Island', 'Norfolk Island'),
    ('Northern Mariana Islands', 'Northern Mariana Islands'),
    ('Norway', 'Norway'),
    ('Oman', 'Oman'),
    ('Pakistan', 'Pakistan'),
    ('Palau', 'Palau'),
    ('Palestinian Territory, Occupied', 'Palestinian Territory, Occupied'),
    ('Panama', 'Panama'),
    ('Papua New Guinea', 'Papua New Guinea'),
    ('Paraguay', 'Paraguay'),
    ('Peru', 'Peru'),
    ('Philippines', 'Philippines'),
    ('Pitcairn', 'Pitcairn'),
    ('Poland', 'Poland'),
    ('Portugal', 'Portugal'),
    ('Puerto Rico', 'Puerto Rico'),
    ('Qatar', 'Qatar'),
    ('Reunion', 'Reunion'),
    ('Romania', 'Romania'),
    ('Russia', 'Russia'),
    ('Rwanda', 'Rwanda'),
    ('Saint Helena', 'Saint Helena'),
    ('Saint Kitts And Nevis', 'Saint Kitts And Nevis'),
    ('Saint Lucia', 'Saint Lucia'),
    ('Saint Pierre And Miquelon', 'Saint Pierre And Miquelon'),
    ('Saint Vincent And The Grenadines', 'Saint Vincent And The Grenadines'),
    ('Samoa', 'Samoa'),
    ('San Marino', 'San Marino'),
    ('Sao Tome And Principe', 'Sao Tome And Principe'),
    ('Saudi Arabia', 'Saudi Arabia'),
    ('Senegal', 'Senegal'),
    ('Serbia', 'Serbia'),
    ('Seychelles', 'Seychelles'),
    ('Sierra Leone', 'Sierra Leone'),
    ('Singapore', 'Singapore'),
    ('Slovakia', 'Slovakia'),
    ('Slovenia', 'Slovenia'),
    ('Solomon Islands', 'Solomon Islands'),
    ('Somalia', 'Somalia'),
    ('South Africa', 'South Africa'),
    ('South Georgia And The South Sandwich Islands', 'South Georgia And The South Sandwich Islands'),
    ('South Sudan', 'South Sudan'),
    ('Spain', 'Spain'),
    ('Sri Lanka', 'Sri Lanka'),
    ('Sudan', 'Sudan'),
    ('Suriname', 'Suriname'),
    ('Svalbard And Jan Mayen', 'Svalbard And Jan Mayen'),
    ('Swaziland', 'Swaziland'),
    ('Sweden', 'Sweden'),
    ('Switzerland', 'Switzerland'),
    ('Syrian Arab Republic', 'Syrian Arab Republic'),
    ('Taiwan', 'Taiwan'),
    ('Tajikistan', 'Tajikistan'),
    ('Tanzania, United Republic Of', 'Tanzania, United Republic Of'),
    ('Thailand', 'Thailand'),
    ('Timor-Leste', 'Timor-Leste'),
    ('Togo', 'Togo'),
    ('Tokelau', 'Tokelau'),
    ('Tonga', 'Tonga'),
    ('Trinidad And Tobago', 'Trinidad And Tobago'),
    ('Tunisia', 'Tunisia'),
    ('Turkey', 'Turkey'),
    ('Turkmenistan', 'Turkmenistan'),
    ('Turks And Caicos Islands', 'Turks And Caicos Islands'),
    ('Tuvalu', 'Tuvalu'),
    ('U.S. Minor Outlying Islands', 'U.S. Minor Outlying Islands'),
    ('Uganda', 'Uganda'),
    ('Ukraine', 'Ukraine'),
    ('United Arab Emirates', 'United Arab Emirates'),
    ('United Kingdom', 'United Kingdom'),
    ('Uruguay', 'Uruguay'),
    ('Uzbekistan', 'Uzbekistan'),
    ('Vanuatu', 'Vanuatu'),
    ('Venezuela', 'Venezuela'),
    ('Viet Nam', 'Viet Nam'),
    ('Virgin Islands, British', 'Virgin Islands, British'),
    ('Virgin Islands, U.S.', 'Virgin Islands, U.S.'),
    ('Wallis And Futuna', 'Wallis And Futuna'),
    ('Western Sahara', 'Western Sahara'),
    ('Yemen', 'Yemen'),
    ('Zambia', 'Zambia'),
    ('Zimbabwe', 'Zimbabwe'),
    ('Other', 'Other'),
)
DENIED_COUNTRIES = [
    'Sudan',
    "Korea, Democratic People's Republic Of",
    'Iran, Islamic Republic Of',
    'Cuba',
    'Syrian Arab Republic',
]
DEPARTMENT_CHOICES = (
    ('Anesthesiology,Perioperative,Pain Medicine', 'Anesthesiology,Perioperative,Pain Medicine'),
    ('Biochemistry', 'Biochemistry'),
    ('Cardiothoracic Surgery', 'Cardiothoracic Surgery'),
    ('Centers - School of Medicine', 'Centers - School of Medicine'),
    ('Chemical and Systems Biology', 'Chemical and Systems Biology'),
    ('Comparative Medicine', 'Comparative Medicine'),
    ('Dermatology', 'Dermatology'),
    ('Developmental Biology', 'Developmental Biology'),
    ('Genetics Operations', 'Genetics Operations'),
    ('Health Research and Policy', 'Health Research and Policy'),
    ('Medicine', 'Medicine'),
    ('Microbiology and Immunology', 'Microbiology and Immunology'),
    ('Molecular and Cellular Physiology', 'Molecular and Cellular Physiology'),
    ('Neurobiology', 'Neurobiology'),
    ('Neurology', 'Neurology'),
    ('Neurosurgery', 'Neurosurgery'),
    ('Obstetrics & Gynecology', 'Obstetrics & Gynecology'),
    ('Ophthalmology', 'Ophthalmology'),
    ('Orthopaedic Surgery', 'Orthopaedic Surgery'),
    ('Otolaryngology/Head & Neck Surgery', 'Otolaryngology/Head & Neck Surgery'),
    ('Pathology', 'Pathology'),
    ('Pediatrics', 'Pediatrics'),
    ('Psychiatry and Behavioral Sciences', 'Psychiatry and Behavioral Sciences'),
    ('Radiation Oncology', 'Radiation Oncology'),
    ('Radiology', 'Radiology'),
    ('School of Medicine', 'School of Medicine'),
    ('SoM - Basic Science Pool', 'SoM - Basic Science Pool'),
    ('SoM - Bio-X/Clark', 'SoM - Bio-X/Clark'),
    ('SoM - Bioengineering', 'SoM - Bioengineering'),
    ('SoM - Clinical Science Pool', 'SoM - Clinical Science Pool'),
    ('SoM - Other Departments', 'SoM - Other Departments'),
    ("SoM Dean's Office Administrative Units", "SoM Dean's Office Administrative Units"),
    ('SoM Non Cap Projects', 'SoM Non Cap Projects'),
    ('Stanford Cancer/Stem Cell Biology', 'Stanford Cancer/Stem Cell Biology'),
    ('Stanford Institutes of Medicine', 'Stanford Institutes of Medicine'),
    ('Structural Biology Department', 'Structural Biology Department'),
    ('Surgery', 'Surgery'),
    ('Urology', 'Urology'),
    ('Urology - Administration', 'Urology - Administration'),
    ('Urology - Divisions', 'Urology - Divisions'),
)
GENDER_CHOICES = (
    ('', '-----'),
    ('f', 'Female'),
    ('m', 'Male'),
)
PATIENT_POPULATION_CHOICES = (
    ('Adult', 'Adult'),
    ('Pediatric', 'Pediatric'),
    ('Both', 'Both'),
    ('None', 'None'),
)
PHYSICIAN_STATUS_CHOICES = (
    ('Active', 'Active'),
    ('Resident', 'Resident'),
    ('Fellow', 'Fellow'),
    ('Retired', 'Retired'),
    ('Inactive', 'Inactive'),
)
PROFESSIONAL_DESIGNATION_CHOICES = (
    ('AuD', 'AuD'),
    ('DDS', 'DDS'),
    ('DO', 'DO'),
    ('MD', 'MD'),
    ('MD,PhD', 'MD,PhD'),
    ('MBBS', 'MBBS'),
    ('NP', 'NP'),
    ('PA', 'PA'),
    ('PharmD', 'PharmD'),
    ('PhD', 'PhD'),
    ('RN', 'RN'),
    ('Other', 'Other'),
    ('None', 'None'),
)
PROFESSIONAL_DESIGNATIONS_EXTRA_REQUIREMENTS = [
    'license_number',
    'license_country',
    'physician_status',
    'patient_population',
    'specialty',
]
PROFESSIONAL_DESIGNATIONS_WITH_EXTRA_REQUIREMENTS = [
    'DO',
    'MD',
    'MD,PhD',
    'MBBS',
]
STATE_CHOICES = (
    ('AL', 'Alabama'),
    ('AK', 'Alaska'),
    ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DE', 'Deleware'),
    ('DC', 'District of Columbia'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('IA', 'Iowa'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MA', 'Massachusetts'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MS', 'Mississippi'),
    ('MO', 'Missouri'),
    ('MT', 'Montana'),
    ('NE', 'Nebraska'),
    ('NV', 'Nevada'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NY', 'New York'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming'),
)
